# Generated by Django 3.0.6 on 2020-10-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('heading', models.CharField(default='', max_length=60)),
                ('category', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=800)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
