# Generated by Django 3.0.6 on 2020-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
