# Generated by Django 3.0.6 on 2020-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pincode', models.CharField(max_length=30)),
            ],
        ),
    ]
